export let BATCH_SIZE_OF_DAILY_PROCESSING_CONSUMERS = 1000;
export let BATCH_SIZE_OF_DAILY_PROCESSING_PUBLISHERS = 1000;
export let BATCH_SIZE_OF_DAILY_PROCESSING_CONUMSERS_FOR_ONE_PUBLISHER = 100;
export let BATCH_SIZE_OF_MONTHLY_RPOCESSING_CONSUMERS = 1000;
export let CACHE_SIZE_OF_GET_SEASON_PUBLISHER_AND_GRADE = 10000;
export let CACHE_SIZE_OF_GET_VIDEO_DURATION_AND_SIZE = 10000;
export let COLD_START_MONTH_FOR_PUBLISHERS = "2024-10";
export let BATCH_SIZE_OF_LOADING_PUBLISHERS = 1000;
